local-library/local-library/catalog/urls.py
from django.urls import path, include, re_path

from . import views


urlpatterns = [
    path('', views.index, name='index'),
    path('books/', views.BookListView.as_view(), name='books'),
    re_path(r'^book/(?P<pk>\d+)$', views.BookDetailView.as_view(), name='book-detail'),
    path('authors/', views.AuthorListView.as_view(), name='authors'),
    re_path(r'^author/(?P<pk>\d+)$', views.AuthorDetailView.as_view(), name='author-detail'),
]

urlpatterns += [
    path('mybooks/', views.LoanedBooksByUserListView.as_view(), name='my-borrowed'),
    path(r'borrowed/', views.LoanedBooksAllListView.as_view(), name='all-borrowed'),
]

local-library/local-library/library/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.contrib import admin


urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls')),
]

local-library/local-library/catalog/models.py
import uuid

from django.db import models
from django.urls import reverse
from datetime import date
from django.conf import settings


class Genre(models.Model):
    
    name = models.CharField(verbose_name='Название жанра', max_length=200, unique=True, help_text='Название жанра (Научная фантастик, психология и т.п.)')
    
    
    def __str__(self) -> str:
        
        return self.name
    
    def get_absolute_url(self) -> str:

        return reverse('genre-detail', args=[str(self.id)])
    
    
    class Meta:
        
        ordering = ['name']
        verbose_name = 'Жанр'
        verbose_name_plural = 'Жанры'
    

class Book(models.Model):
    
    title = models.CharField(verbose_name='Название книги', max_length=200, help_text='Название книги')
    summary = models.TextField(verbose_name='Описание', max_length=1500, help_text='Краткое описание книги')
    isbn = models.CharField(verbose_name='ISBN', max_length=25, help_text='13-ти символьный <a href="https://www.isbn-international.org/content/what-isbn''">ISBN номер</a>')
    genre = models.ManyToManyField(Genre, verbose_name='Жанр', help_text='Жанры, к которым относится книга')
    
    language = models.ForeignKey('Language', verbose_name='Язык', on_delete=models.DO_NOTHING, help_text='Язык, на котором написана книга')
    author = models.ForeignKey('Author', verbose_name='Автор', on_delete=models.SET_NULL, null=True, help_text='Автор книги')
    
    
    def __str__(self) -> str:
        
        return self.title
    
    def get_absolute_url(self) -> str:
        
        return reverse('book-detail', args=[str(self.id)])
    
    
    class Meta:
        
        ordering = ['author', 'title', 'language']
        verbose_name = 'Книгу'
        verbose_name_plural = 'Книги'
    
    
class BookInstance(models.Model):
    
    id = models.UUIDField(primary_key=True, verbose_name='UUID', default=uuid.uuid4, help_text='Уникальный идентификатор экземпляря книги')
    imprint = models.CharField(verbose_name='Издание', max_length=200, help_text='Дата издания книги, издатель и т.п.')
    due_back = models.DateField(verbose_name='Дата возрата', null=True, blank=True, help_text='Дата, когда экземпляр должен быть возвращен')
    
    book = models.ForeignKey('Book', verbose_name='Книга', on_delete=models.RESTRICT, null=True, help_text='Книга, к которой относится экземпляр')
    
    borrower = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='Владелец', on_delete=models.SET_NULL, null=True, blank=True, help_text='Человек, который забрал экземпляр')
    
    
    LOAN_STATUS = (
        ('m', 'На обслуживании'),
        ('o', 'Выдан'),
        ('a', 'Доступен'),
        ('r', 'Забронирован')
    )
    
    status = models.CharField(verbose_name='Статус экземпляра', max_length=1, choices=LOAN_STATUS, blank=True, default='m', help_text='Доступность экземпляр')
    
    
    class Meta:
        
        ordering = ['book', 'due_back']
        verbose_name = 'Экземпляр книги'
        verbose_name_plural = 'Экземпляры книг'
        permissions = (("can_mark_returned", "Set book as returned"),)
        
    
    def get_absolute_url(self) -> str:

        return reverse('bookinstance-detail', args=[str(self.id)])
    
    def __str__(self) -> str:
        
        return '%s (%s)' % (self.id, self.book.title)
    
    @property
    def is_overdue(self):
        
        return bool(self.due_back and date.today() > self.due_back)
    

class Author(models.Model):
    
    first_name = models.CharField(verbose_name='Имя', max_length=100, help_text='Имя и отчество (опционально) автора')
    last_name = models.CharField(verbose_name='Фамилия', max_length=100, help_text='Фамилия автора')
    date_of_birth = models.DateField(verbose_name='Дата рождения', null=True, blank=True, help_text='Дата рождения автора')
    date_of_death = models.DateField(verbose_name='Дата смерти', null=True, blank=True, help_text='Дата смерти автора')
    
    
    class Meta:

        ordering = ['last_name', 'first_name']
        verbose_name = 'Автора'
        verbose_name_plural = 'Авторы'

    
    def get_absolute_url(self):
        
        return reverse('author-detail', args=[str(self.id)])
    
    def __str__(self) -> str:
        
        return '%s, %s' % (self.last_name, self.first_name)
   

class Language(models.Model):
    
    name = models.CharField(verbose_name='Язык', max_length=100, unique=True, help_text='Язык, на котором написан оригинал')
    
    
    class Meta:
        
        ordering = ['name']
        verbose_name = 'Язык'
        verbose_name_plural = 'Языки'
    
    
    def get_absolute_url(self) -> str:

        return reverse('language-detail', args=[str(self.id)])
    
    def __str__(self) -> str:
        
        return '%s' % (str(self.name))

local-library/local-library/catalog/views.py
from django.shortcuts import render
from django.views import generic
from django.http import HttpRequest, HttpResponse
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin

from .models import Book, Author, BookInstance, Genre


def index(request: HttpRequest) -> HttpResponse:
    
    num_books = Book.objects.count()
    num_instances = BookInstance.objects.count()
    num_authors = Author.objects.count()
    
    num_instances_available = BookInstance.objects.filter(status__exact = 'a').count()

    num_word_fiction_genre = Genre.objects.filter(name__exact = 'фантастика').count()
    
    num_visits = request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits + 1
    
    context = {
        'num_books': num_books,
        'num_instances': num_instances,
        'num_instances_available': num_instances_available,
        'num_authors': num_authors,
        'num_word_fiction_genre': num_word_fiction_genre,
        'num_visits': num_visits,
    }
    
    return render(request, 'index.html', context)


class BookListView(generic.ListView):
    
    model = Book
    paginate_by = 10

class BookDetailView(generic.DetailView):
    
    model = Book


class AuthorListView(generic.ListView):
    
    model = Author
    paginate_by = 3

class AuthorDetailView(generic.DetailView):
    
    model = Author


class LoanedBooksByUserListView(LoginRequiredMixin,generic.ListView):
    
    model = BookInstance
    template_name = 'catalog/bookinstance_list_borrowed_user.html'
    paginate_by = 5
    
    def get_queryset(self):
        return (
            BookInstance.objects.filter(borrower=self.request.user)
            .filter(status__exact='o')
            .order_by('due_back')
        )


class LoanedBooksAllListView(PermissionRequiredMixin, generic.ListView):
    
    model = BookInstance
    permission_required = 'catalog.can_mark_returned'
    template_name = 'catalog/bookinstance_list_borrowed_all.html'
    paginate_by = 10

    def get_queryset(self):
        
        return BookInstance.objects.filter(status__exact='o').order_by('due_back')

local-library/local-library/catalog/templates/base_generic.html
<!DOCTYPE html>
<html lang="ru">
  <head>
    {% block title %}
      <title>Сайт местной библиотеки</title>
    {% endblock %}
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
      crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}" />
  </head>
  <body>
    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-2">
          {% block sidebar %}
            <ul class="sidebar-nav">
              <li><a href="{% url 'index' %}">Домашняя страница</a></li>
              <li><a href="{% url 'books' %}">Список книг</a></li>
              <li><a href="{% url 'authors' %}">Список авторов</a></li>
            </ul>
          {% endblock %}
        </div>
        <div class="col-sm-10 ">
          {% block content %}{% endblock %}
          {% block pagination %}
            {% if is_paginated %}
                <div class="pagination">
                    <span class="page-links">
                        {% if page_obj.has_previous %}
                            <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">пред.</a>
                        {% endif %}
                        <span class="page-current">
                            Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}.
                        </span>
                        {% if page_obj.has_next %}
                            <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">след.</a>
                        {% endif %}
                    </span>
                </div>
            {% endif %}
          {% endblock %}
        </div>
      </div>
    </div>
  </body>
</html>

local-library/local-library/catalog/templates/catalog/author_detail.html
{% extends "base_generic.html" %}

{% block title %}
  <title>{{ author.last_name }}, {{ author.first_name }}</title>
{% endblock %}

{% block content %}
  <h1>{{ author.last_name }}, {{ author.first_name }}</h1>

  <p class="text-muted">
    {{ author.date_of_birth }} - 
        {% if author.date_of_death %}
            {{ author.date_of_death }}
            {% else %}По сей день
        {% endif %} 
  </p>

  <div style="margin-left:20px;margin-top:20px">
    <h4>Книги автора</h4>

    {% for book in author.book_set.all %}
      <hr />
      <a href="{% url 'book-detail' book.pk %}"><p><strong>{{ book.title }}</strong></p></a>
      <p class="text-muted" style="margin-left:5px;">{{ book.summary }}</p>
    {% endfor %}
  </div>
{% endblock %}

local-library/local-library/catalog/templates/catalog/author_list.html
{% extends "base_generic.html" %}

{% block title %}
  <title>Авторы</title>
{% endblock %}

{% block content %}
  <h1>Список авторов</h1>
  {% if author_list %}
    <ul>
      {% for author in author_list %}
      <li>
        <a href="{{ author.get_absolute_url }}">{{ author.last_name }}, {{ author.first_name }}</a>
      </li>
      {% endfor %}
    </ul>
  {% else %}
    <p>Нет данных об авторах</p>
  {% endif %}
{% endblock %}

local-library/local-library/catalog/templates/catalog/book_detail.html
{% extends "base_generic.html" %}

{% block title %}
  <title>{{ book.title }}</title>
{% endblock %}

{% block content %}
  <h1>{{ book.title }}</h1>

  <p><strong>Автор: </strong><a href="{{ book.author.get_absolute_url }}">{{ book.author }}</a></p>
  <p><strong>Краткое описание:</strong> {{ book.summary }}</p>
  <p><strong>ISBN номер:</strong> {{ book.isbn }}</p>
  <p><strong>Язык книги:</strong> {{ book.language }}</p> 
  <p><strong>Жанры:</strong> {{ book.genre.all|join:", " }}</p>

  <div style="margin-left:20px;margin-top:20px">
    <h4>Экземпляры</h4>

    {% for copy in book.bookinstance_set.all %}
      <hr />
      <p
        class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'm' %}text-danger{% else %}text-warning{% endif %}">
        {{ copy.get_status_display }}
      </p>
      {% if copy.status != 'a' %}
        <p><strong>Должен быть возвращён:</strong> {{ copy.due_back }}</p>
      {% endif %}
      <p><strong>Издание:</strong> {{ copy.imprint }}</p>
      <p class="text-muted"><strong>UUID:</strong> {{ copy.id }}</p>
    {% endfor %}
  </div>
{% endblock %}

local-library/local-library/catalog/templates/catalog/book_list.html
{% extends "base_generic.html" %}

{% block title %}
  <title>Список литературы</title>
{% endblock %}

{% block content %}
  <h1>Список литературы</h1>
  {% if book_list %}
    <ul>
      {% for book in book_list %}
      <li>
        <a href="{{ book.get_absolute_url }}">{{ book.title }}</a> ({{book.author}})
      </li>
      {% endfor %}
    </ul>
  {% else %}
    <p>В библиотеки нет книг</p>
  {% endif %}
{% endblock %}

local-library/local-library/catalog/templates/catalog/bookinstance_list_borrowed_all.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Все изъятые экземпляры</h1>

    {% if bookinstance_list %}
    <ul>

      {% for bookinst in bookinstance_list %} 
      <li class="{% if bookinst.is_overdue %}text-danger{% endif %}">
        <a href="{% url 'book-detail' bookinst.book.pk %}">{{bookinst.book.title}}</a> ({{ bookinst.due_back }}) {% if user.is_staff %}- {{ bookinst.borrower }}{% endif %}
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>Изъятых экземпляров нет.</p>
    {% endif %}       
{% endblock %}

local-library/local-library/catalog/templates/catalog/bookinstance_list_borrowed_user.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Изъятые экземпляры</h1>

    {% if bookinstance_list %}
    <ul>

      {% for bookinst in bookinstance_list %}
      <li class="{% if bookinst.is_overdue %}text-danger{% endif %}">
        <a href="{% url 'book-detail' bookinst.book.pk %}">{{ bookinst.book.title }}</a> ({{ bookinst.due_back }})
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>Изъятых экземпляров нет.</p>
    {% endif %}
{% endblock %}

local-library/local-library/catalog/templates/index.html
{% extends "base_generic.html" %}

{% block title %}
  <title>Домашняя страница библиотеки</title>
{% endblock %}

{% block content %}
  <h1>Домашняя страница сайта</h1>
  <h2>Динамически изменяемое наполнение</h2>
  <p>Библиотека ведёт подсчёт метрикам:</p>
  <ul>
    <li><strong>Всего книг:</strong> {{ num_books }}</li>
    <li><strong>Количество экземпляров:</strong> {{ num_instances }}</li>
    <li><strong>Количество доступных экземпляров:</strong> {{ num_instances_available }}</li>
    <li><strong>Количество авторов:</strong> {{ num_authors }}</li>
    <li><strong>Слово 'Фантастика' встречается в жанрах </strong> {{ num_authors }} <strong> раз </strong></li>
  </ul>

  <p>
    Вы посещали эту страницу {{ num_visits }} {% if num_visits == 1 %} раз {% else %} раза! {% endif %}
  </p>
{% endblock %}